# Generated by Django 3.2.11 on 2022-01-31 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_hosted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(default=None, null=True, related_name='events_invited', to=settings.AUTH_USER_MODEL),
        ),
    ]
