# Generated by Django 3.2.12 on 2022-02-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220131_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtime',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_times', to='events.event'),
        ),
    ]
