# Generated by Django 3.2.12 on 2022-02-07 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20220207_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='state',
            field=models.CharField(choices=[('waiting_response', 'Waiting for attendance from user'), ('waiting_suggestion', 'Waiting for date suggestion from user'), ('waiting_validation', 'Waiting for date validation from user'), ('waiting_for_others', 'Waiting for other users to respond to suggestions'), ('is_attending', 'Is able to attend event'), ('is_not_attending', 'Has elected to not attend event')], default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='events.event'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
