# Generated by Django 3.2.11 on 2022-02-10 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_auto_20220207_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('event_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event_time', to='events.eventtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event_time', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
