# Generated by Django 3.2.11 on 2022-02-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_usereventtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventtime',
            name='has_seen',
            field=models.BooleanField(default=False),
        ),
    ]
