# Generated by Django 3.2.11 on 2022-02-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_usereventtime_explicit_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField()),
                ('input_text', models.CharField(max_length=256)),
                ('interpreted_start', models.DateTimeField()),
                ('interpreted_end', models.DateTimeField()),
            ],
        ),
    ]
