# Generated by Django 3.2.11 on 2022-02-17 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_suggesteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggesteddate',
            name='user_event',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_date', to='events.userevent'),
            preserve_default=False,
        ),
    ]
