# Generated by Django 3.2.11 on 2022-02-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_suggesteddate_user_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggesteddate',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
