# Generated by Django 3.2.11 on 2024-01-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_suggesteddate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereventtime',
            name='explicit_response',
            field=models.CharField(choices=[('waiting_response', 'Has not answered for this event time'), ('can_come', 'Has explicitly said they can come to this time slot'), ('cannot_come', 'Has explicitly said they cannot come to this time slot')], default='waiting_response', max_length=256, null=True),
        ),
    ]
