# Generated by Django 3.2.11 on 2022-01-31 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=512, null=True)),
                ('is_available', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DateAvailability',
            fields=[
                ('availability_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='availabilities.availability')),
                ('date_time_start', models.DateTimeField()),
                ('date_time_end', models.DateTimeField()),
            ],
            bases=('availabilities.availability',),
        ),
        migrations.CreateModel(
            name='WeekAvailability',
            fields=[
                ('availability_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='availabilities.availability')),
                ('week_availability', models.CharField(choices=[('weekend', 'Weekend'), ('weekday', 'Weekday')], max_length=256)),
            ],
            bases=('availabilities.availability',),
        ),
        migrations.CreateModel(
            name='RepeatedDateAvailability',
            fields=[
                ('dateavailability_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='availabilities.dateavailability')),
                ('is_repeated_weekly', models.BooleanField(default=False)),
                ('is_repeated_monthly', models.BooleanField(default=False)),
            ],
            bases=('availabilities.dateavailability',),
        ),
    ]
