# Generated by Django 3.2.11 on 2022-01-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availabilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateavailability',
            name='availability_ptr',
        ),
        migrations.RemoveField(
            model_name='repeateddateavailability',
            name='dateavailability_ptr',
        ),
        migrations.RemoveField(
            model_name='weekavailability',
            name='availability_ptr',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='DateAvailability',
        ),
        migrations.DeleteModel(
            name='RepeatedDateAvailability',
        ),
        migrations.DeleteModel(
            name='WeekAvailability',
        ),
    ]
