# Generated by Django 3.2.11 on 2022-01-31 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availabilities', '0003_dateavailability_repeateddateavailability_weekavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeateddateavailability',
            name='dateavailability_ptr',
        ),
        migrations.RemoveField(
            model_name='weekavailability',
            name='user',
        ),
        migrations.DeleteModel(
            name='DateAvailability',
        ),
        migrations.DeleteModel(
            name='RepeatedDateAvailability',
        ),
        migrations.DeleteModel(
            name='WeekAvailability',
        ),
    ]
