# Generated by Django 3.2.11 on 2024-02-07 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0002_usercontactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_contact_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
