# Generated by Django 3.2.11 on 2024-03-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_usercontactinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactinfo',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
