# Generated by Django 3.2.11 on 2024-02-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_usercontactinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usereventmessage',
            old_name='explicit_response',
            new_name='direction',
        ),
    ]
