# Generated by Django 3.2.11 on 2024-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_rename_explicit_response_usereventmessage_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontactinfo',
            name='whatsapp_phone_number',
        ),
        migrations.AddField(
            model_name='usercontactinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
